### ISSUE TITLE
Past data

### ISSUE THREAD

**Issue by Laforeta** [dragonjet/kancolle-decode#1]
Hi DJ, 

Would it be too much trouble to ask for any old versions of api_start2 files you might have? I working on a collection of previous seasonal art (for modding purposes) and it would make my life much easier to have access to old data, especially the numbers in api_mst_shipgraph. 

I had been trying to get the data off http://kancolle.jetri.co but it went offline before I could come up with a good way to parse the data in the right format. 

Cheers and thanks again for all your work
Laforet

**Comment by dragonjet** [comment]
I removed the files generating the error on http://kancolle.jetri.co/

the good thing is, the filenames in `mst_shipgraph` does not change, the swf file itself is reuploaded/replaced when there is a seasonal art, and reverted back to the original swf after the season, all on the same filename.

what happens last time to seasonal art though is that after being reverted to original, they get added back as `api_id` 900+. but now I look at http://kancolle.jetri.co/decodes/extra/browse there's no ID 900+

**Comment by Laforeta** [comment]
Thank you very much. What I am after are the positional offsets defined in mst_shipgraph (e.g. api_boko_n) which changes according to the image on display. Without these numbers the sprites won't be displayed in the correct location. 

A lot of data on past seasonal art have been trimmed from api_start2 since July and they no longer assigned with shipID, I have not looked into this but the it looks like AlbumMain have access to a list of filenames somewhere. In any case the archived versions on server right now are incomplete (missing the high-res images 17&19), so some manual stamp collecting is unavoidable. 

I will publish a list containing all the useful information once it is done.

**Comment by dragonjet** [comment]
:+1: sounds good, if you still need the list of raw json, I could probably download it from the server and push to this repo. though it probably will not look like the one from the server, where the update changes are determined by comparing latest master to the previous - but uploading all master files at once will confuse it.
